// @generated by montrs-icons-codegen. DO NOT EDIT.
//
// Collection glyph tables stored as DEFLATE-compressed binary blobs.
//
// The ~13 MB of inline SVG source that used to live in this file is now a set
// of small `.bin` blobs (one per collection) that are decompressed lazily on
// first use. This keeps the compiled WASM bundle roughly 9 MB smaller while
// preserving the `&'static [CollectedGlyph]` API.
//
// Binary layout (little-endian):
//   u32 icon_count
//   per icon: u16 name_len + bytes, u32 svg_len + bytes,
//             u8 viewbox_len + bytes, u8 fill_len + bytes,
//             u8 stroke_len + bytes

use super::CollectedGlyph;
use std::sync::OnceLock;

struct Reader<'a> {
    bytes: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, pos: 0 }
    }

    fn u8(&mut self) -> usize {
        let value = self.bytes[self.pos] as usize;
        self.pos += 1;
        value
    }

    fn u16(&mut self) -> usize {
        let value = u16::from_le_bytes([
            self.bytes[self.pos],
            self.bytes[self.pos + 1],
        ]) as usize;
        self.pos += 2;
        value
    }

    fn u32(&mut self) -> usize {
        let value = u32::from_le_bytes([
            self.bytes[self.pos],
            self.bytes[self.pos + 1],
            self.bytes[self.pos + 2],
            self.bytes[self.pos + 3],
        ]) as usize;
        self.pos += 4;
        value
    }

    fn string(&mut self, len: usize) -> &'a str {
        let slice = &self.bytes[self.pos..self.pos + len];
        self.pos += len;
        std::str::from_utf8(slice)
            .expect("montrs-icons: collection blob is not valid UTF-8")
    }
}

/// Decompress a collection blob and leak its strings/records to obtain a
/// `&'static` table (the data lives for the process lifetime, which is what
/// the `CollectedGlyph` API requires).
fn load(blob: &'static [u8]) -> &'static [CollectedGlyph] {
    let raw = miniz_oxide::inflate::decompress_to_vec(blob)
        .expect("montrs-icons: corrupt collection blob");
    let raw: &'static [u8] = Box::leak(raw.into_boxed_slice());

    let mut reader = Reader::new(raw);
    let count = reader.u32();
    let mut glyphs: Vec<CollectedGlyph> = Vec::with_capacity(count);
    for _ in 0..count {
        let name_len = reader.u16();
        let name = reader.string(name_len);
        let svg_len = reader.u32();
        let svg = reader.string(svg_len);
        let viewbox_len = reader.u8();
        let viewbox = reader.string(viewbox_len);
        let fill_len = reader.u8();
        let fill = reader.string(fill_len);
        let stroke_len = reader.u8();
        let stroke = reader.string(stroke_len);
        glyphs.push(CollectedGlyph {
            name,
            svg,
            viewbox,
            fill,
            stroke,
        });
    }
    Box::leak(glyphs.into_boxed_slice())
}

macro_rules! collection_table {
    ($name:ident, $feature:literal, $file:literal) => {
        #[cfg(feature = $feature)]
        pub fn $name() -> &'static [CollectedGlyph] {
            static TABLE: OnceLock<&'static [CollectedGlyph]> =
                OnceLock::new();
            TABLE.get_or_init(|| load(include_bytes!($file)))
        }
    };
}

collection_table!(radix_icons, "col-radix", "radix.bin");
collection_table!(tabler_icons, "col-tabler", "tabler.bin");
collection_table!(iconoir_icons, "col-iconoir", "iconoir.bin");
collection_table!(phosphor_icons, "col-phosphor", "phosphor.bin");
collection_table!(mdi_icons, "col-mdi", "mdi.bin");
collection_table!(bootstrap_icons, "col-bootstrap", "bootstrap.bin");
collection_table!(simple_icons_icons, "col-simple-icons", "simple-icons.bin");
collection_table!(cryptocurrency_icons, "col-cryptocurrency", "cryptocurrency.bin");
