[project]
name = "todo-example"
version = "0.1.0"

[serve]
site-addr = "0.0.0.0:3000"
reload-port = 3001
tailwind-input-file = "style/main.css"
site-root = "target/site"
site-pkg-dir = "pkg"
lib-features = ["hydrate"]
lib-default-features = false

[build]
target = "index.html"

[tasks]
fmt = { command = "cargo fmt --all", category = "Quality" }
lint = { command = "cargo clippy -- -D warnings", category = "Quality" }
test = { command = "cargo test", category = "Testing" }