// بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيم
// This file is part of montrs.
// Copyright (C) 2026-Present Afsall Inc.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Alternatively, this file is available under the MIT License:
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

//! MontRS lockfile — deterministic tool version locking.
//!
//! Records pre-resolved tool versions, download URLs, checksums, and
//! platform-specific info so installs are reproducible across machines.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    path::{Path, PathBuf},
};

/// The lockfile header prefix marking auto-generated files.
pub const LOCKFILE_HEADER_PREFIX: &str =
    "# @generated - this file is auto-generated by `montrs lock`";

/// The lockfile filename.
pub const LOCKFILE_FILENAME: &str = "montrs.lock";

/// A single locked tool version.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockfileTool {
    /// The resolved version string.
    pub version: String,
    /// The backend that resolved this version.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<String>,
    /// Backend-specific options.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub options: BTreeMap<String, String>,
    /// Platform-specific download info.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub platforms: BTreeMap<String, PlatformInfo>,
}

/// Platform-specific download information.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PlatformInfo {
    /// The download URL for this platform.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// SHA256 checksum of the artifact.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    /// The binary names installed.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub bins: Vec<String>,
}

/// The full lockfile.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MontrsLock {
    /// Lockfile version/format version.
    #[serde(default = "default_format_version")]
    pub format_version: u32,
    /// Locked tools: name -> list of locked versions (multiple allow overlapping).
    #[serde(default)]
    pub tools: BTreeMap<String, Vec<LockfileTool>>,
    /// The config files that produced this lockfile.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub config_sources: Vec<String>,
}

fn default_format_version() -> u32 {
    1
}

impl MontrsLock {
    pub fn new() -> Self {
        Self {
            format_version: default_format_version(),
            tools: BTreeMap::new(),
            config_sources: Vec::new(),
        }
    }

    /// Add or replace a locked tool version.
    pub fn set_tool(&mut self, name: &str, tool: LockfileTool) {
        self.tools.insert(name.to_string(), vec![tool]);
    }

    /// Add a locked tool version (appends to existing versions for the tool).
    pub fn add_tool(&mut self, name: &str, tool: LockfileTool) {
        self.tools.entry(name.to_string()).or_default().push(tool);
    }

    /// Look up a locked version for a tool on the current platform.
    pub fn resolved_version(&self, name: &str) -> Option<&LockfileTool> {
        self.tools.get(name)?.first()
    }

    /// Whether a tool is locked.
    pub fn has(&self, name: &str) -> bool {
        self.tools.contains_key(name)
    }

    /// Number of locked tools.
    pub fn len(&self) -> usize {
        self.tools.len()
    }

    pub fn is_empty(&self) -> bool {
        self.tools.is_empty()
    }

    /// Get the current platform key (os-arch).
    pub fn current_platform() -> String {
        format!("{}-{}", std::env::consts::OS, std::env::consts::ARCH)
    }

    /// Compute a content hash of the lockfile (for cache invalidation).
    pub fn content_hash(&self) -> String {
        let canonical = serde_json::to_string(self).unwrap_or_default();
        hex::encode(Sha256::digest(canonical.as_bytes()))
    }
}

/// Write a lockfile to disk with the generated header.
pub fn write_lockfile(
    path: &Path,
    lock: &MontrsLock,
) -> Result<(), LockfileError> {
    let mut content = String::new();
    content.push_str(LOCKFILE_HEADER_PREFIX);
    content.push('\n');
    content.push_str(&format!("format_version = {}\n", lock.format_version));
    content.push('\n');

    // Serialize tools section as TOML.
    let toml_str = toml::to_string(&lock)
        .map_err(|e| LockfileError::Serialize(e.to_string()))?;
    // Strip the header fields we already wrote to avoid duplication.
    let toml_str = toml_str
        .lines()
        .filter(|l| !l.starts_with("format_version"))
        .collect::<Vec<_>>()
        .join("\n");
    content.push_str(&toml_str);

    std::fs::write(path, content)?;
    Ok(())
}

/// Read a lockfile from disk.
pub fn read_lockfile(path: &Path) -> Result<MontrsLock, LockfileError> {
    let content = std::fs::read_to_string(path)?;
    parse_lockfile(&content)
}

/// Parse lockfile content (strips the generated header comment).
pub fn parse_lockfile(content: &str) -> Result<MontrsLock, LockfileError> {
    // Strip comment lines so TOML parses cleanly.
    let filtered = content
        .lines()
        .filter(|l| !l.trim_start().starts_with('#') && !l.trim().is_empty())
        .collect::<Vec<_>>()
        .join("\n");
    let lock: MontrsLock = toml::from_str(&filtered)
        .map_err(|e| LockfileError::Parse(e.to_string()))?;
    Ok(lock)
}

/// Default lockfile path for a project root.
pub fn lockfile_path_for_root(root: &Path) -> PathBuf {
    root.join(LOCKFILE_FILENAME)
}

/// Errors from lockfile operations.
#[derive(Debug, thiserror::Error)]
pub enum LockfileError {
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Failed to serialize lockfile: {0}")]
    Serialize(String),
    #[error("Failed to parse lockfile: {0}")]
    Parse(String),
}

/// A file lock for serializing concurrent installs.
#[derive(Debug)]
pub struct LockFile {
    path: PathBuf,
    lock: Option<fslock::LockFile>,
}

impl LockFile {
    pub fn new(path: &Path) -> Self {
        Self {
            path: path.to_path_buf(),
            lock: None,
        }
    }

    /// Acquire an exclusive lock, blocking if needed.
    pub fn lock(&mut self) -> Result<(), LockfileError> {
        if let Some(parent) = self.path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let mut lock = fslock::LockFile::open(&self.path)?;
        lock.lock()?;
        self.lock = Some(lock);
        Ok(())
    }

    /// Try to acquire the lock without blocking.
    pub fn try_lock(&mut self) -> Result<bool, LockfileError> {
        if let Some(parent) = self.path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let mut lock = fslock::LockFile::open(&self.path)?;
        let acquired = lock.try_lock()?;
        if acquired {
            self.lock = Some(lock);
        }
        Ok(acquired)
    }
}

impl Drop for LockFile {
    fn drop(&mut self) {
        if let Some(lock) = &mut self.lock {
            let _ = lock.unlock();
        }
    }
}
