//! Invariant tests for montrs-lockfile.

use montrs_lockfile::*;
use std::{collections::BTreeMap, path::Path};

#[test]
fn test_lockfile_new() {
    let lock = MontrsLock::new();
    assert!(lock.is_empty());
    assert_eq!(lock.format_version, 1);
}

#[test]
fn test_lockfile_set_tool() {
    let mut lock = MontrsLock::new();
    lock.set_tool(
        "rust",
        LockfileTool {
            version: "1.84.0".to_string(),
            backend: Some("core:rust".to_string()),
            options: BTreeMap::new(),
            platforms: BTreeMap::new(),
        },
    );
    assert!(lock.has("rust"));
    assert_eq!(lock.len(), 1);
    let tool = lock.resolved_version("rust").unwrap();
    assert_eq!(tool.version, "1.84.0");
}

#[test]
fn test_lockfile_add_tool() {
    let mut lock = MontrsLock::new();
    lock.add_tool(
        "node",
        LockfileTool {
            version: "20.0.0".to_string(),
            backend: Some("core:node".to_string()),
            options: BTreeMap::new(),
            platforms: BTreeMap::new(),
        },
    );
    lock.add_tool(
        "node",
        LockfileTool {
            version: "18.0.0".to_string(),
            backend: Some("core:node".to_string()),
            options: BTreeMap::new(),
            platforms: BTreeMap::new(),
        },
    );
    let tools = lock.tools.get("node").unwrap();
    assert_eq!(tools.len(), 2);
}

#[test]
fn test_current_platform() {
    let platform = MontrsLock::current_platform();
    assert!(!platform.is_empty());
    assert!(platform.contains('-'));
}

#[test]
fn test_content_hash() {
    let mut lock = MontrsLock::new();
    lock.set_tool(
        "test",
        LockfileTool {
            version: "1.0.0".to_string(),
            backend: None,
            options: BTreeMap::new(),
            platforms: BTreeMap::new(),
        },
    );
    let hash = lock.content_hash();
    assert_eq!(hash.len(), 64); // SHA256 hex
}

#[test]
fn test_write_read_lockfile() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("montrs.lock");
    let mut lock = MontrsLock::new();
    lock.set_tool(
        "rust",
        LockfileTool {
            version: "1.84.0".to_string(),
            backend: Some("core:rust".to_string()),
            options: BTreeMap::new(),
            platforms: BTreeMap::new(),
        },
    );
    write_lockfile(&path, &lock).unwrap();
    assert!(path.exists());
    let read = read_lockfile(&path).unwrap();
    assert_eq!(read.len(), 1);
    assert!(read.has("rust"));
}

#[test]
fn test_parse_lockfile() {
    let content = r#"# @generated - this file is auto-generated by `montrs lock`
format_version = 1

[[tools.rust]]
version = "1.84.0"
backend = "core:rust"
"#;
    let lock = parse_lockfile(content).unwrap();
    assert!(lock.has("rust"));
    assert_eq!(lock.resolved_version("rust").unwrap().version, "1.84.0");
}

#[test]
fn test_platform_info() {
    let info = PlatformInfo {
        url: Some("https://example.com/artifact.tar.gz".to_string()),
        checksum: Some("abc123".to_string()),
        bins: vec!["bin".to_string()],
    };
    assert_eq!(
        info.url.as_deref(),
        Some("https://example.com/artifact.tar.gz")
    );
    assert_eq!(info.bins, vec!["bin"]);
}

#[test]
fn test_lockfile_path() {
    let path = lockfile_path_for_root(Path::new("/tmp/project"));
    assert_eq!(path, Path::new("/tmp/project").join("montrs.lock"));
}

#[test]
fn test_lock_file_lock() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("test.lock");
    let mut lock = LockFile::new(&path);
    // Should succeed without blocking
    lock.lock().unwrap();
    // Lock is released on drop
}

#[test]
fn test_lock_file_try_lock() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("test2.lock");
    let mut lock = LockFile::new(&path);
    let acquired = lock.try_lock().unwrap();
    assert!(acquired);
}

#[test]
fn test_config_sources() {
    let mut lock = MontrsLock::new();
    lock.config_sources.push("montrs.toml".to_string());
    assert_eq!(lock.config_sources, vec!["montrs.toml"]);
}
