[package]
name = "{{crate_name}}"
version.workspace = true
edition.workspace = true

[workspace]
resolver = "2"
members = [".", "e2e"]

[workspace.dependencies]
montrs = { path = "{{project-name}}/packages/montrs" }

[dependencies]
montrs-core = { path = "{{project-name}}/packages/core" }
montrs-auth = { path = "{{project-name}}/packages/auth" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
axum = "0.8"

[[bin]]
name = "api"
path = "src/main.rs"

[[bin]]
name = "{{crate_name}}"
path = "src/main.rs"