// @generated — embedded montrs-ui component registry for `montrs add`.
// Sources are the canonical files in packages/ui/src/components/*.rs.
// Do not edit by hand; re-run `montrs add` development tooling to regenerate.

macro_rules! embed {
    ($name:literal) => {
        include_str!(concat!("../../../ui/src/components/", $name, ".rs"))
    };
}

pub const COMPONENTS: &[(&str, &str)] = &[
    ("accordion", embed!("accordion")),
    ("action_bar", embed!("action_bar")),
    ("alert", embed!("alert")),
    ("alert_dialog", embed!("alert_dialog")),
    ("animate", embed!("animate")),
    ("aspect_ratio", embed!("aspect_ratio")),
    ("attachment", embed!("attachment")),
    ("auto_form", embed!("auto_form")),
    ("avatar", embed!("avatar")),
    ("badge", embed!("badge")),
    ("bento_grid", embed!("bento_grid")),
    ("bottom_nav", embed!("bottom_nav")),
    ("breadcrumb", embed!("breadcrumb")),
    ("bubble", embed!("bubble")),
    ("button", embed!("button")),
    ("button_action", embed!("button_action")),
    ("button_group", embed!("button_group")),
    ("callout", embed!("callout")),
    ("card", embed!("card")),
    ("card_carousel", embed!("card_carousel")),
    ("carousel", embed!("carousel")),
    ("charts", embed!("charts")),
    ("chat", embed!("chat")),
    ("checkbox", embed!("checkbox")),
    ("chips", embed!("chips")),
    ("collapsible", embed!("collapsible")),
    ("command", embed!("command")),
    ("context_menu", embed!("context_menu")),
    ("data_grid", embed!("data_grid")),
    ("data_table", embed!("data_table")),
    ("date_picker", embed!("date_picker")),
    ("date_picker_dual_state", embed!("date_picker_dual_state")),
    ("date_picker_state", embed!("date_picker_state")),
    ("dialog", embed!("dialog")),
    ("direction_provider", embed!("direction_provider")),
    ("drag_and_drop", embed!("drag_and_drop")),
    ("drawer", embed!("drawer")),
    ("dropdown_menu", embed!("dropdown_menu")),
    ("empty", embed!("empty")),
    ("expandable", embed!("expandable")),
    ("faq_transition", embed!("faq_transition")),
    ("field", embed!("field")),
    ("footer", embed!("footer")),
    ("form", embed!("form")),
    ("header", embed!("header")),
    ("hover_card", embed!("hover_card")),
    ("image", embed!("image")),
    ("input", embed!("input")),
    ("input_group", embed!("input_group")),
    ("input_otp", embed!("input_otp")),
    ("input_phone", embed!("input_phone")),
    ("input_prompt", embed!("input_prompt")),
    ("item", embed!("item")),
    ("kbd", embed!("kbd")),
    ("label", embed!("label")),
    ("link", embed!("link")),
    ("marker", embed!("marker")),
    ("marquee", embed!("marquee")),
    ("mask", embed!("mask")),
    ("mask_2", embed!("mask_2")),
    ("menubar", embed!("menubar")),
    ("message", embed!("message")),
    ("multi_select", embed!("multi_select")),
    ("navigation_menu", embed!("navigation_menu")),
    ("pagination", embed!("pagination")),
    ("popover", embed!("popover")),
    ("pressable", embed!("pressable")),
    ("progress", embed!("progress")),
    ("radio_button", embed!("radio_button")),
    ("radio_button_group", embed!("radio_button_group")),
    ("scroll_area", embed!("scroll_area")),
    ("select", embed!("select")),
    ("select_native", embed!("select_native")),
    ("separator", embed!("separator")),
    ("sheet", embed!("sheet")),
    ("shimmer", embed!("shimmer")),
    ("sidenav", embed!("sidenav")),
    ("skeleton", embed!("skeleton")),
    ("slider", embed!("slider")),
    ("sonner", embed!("sonner")),
    ("spinner", embed!("spinner")),
    ("status", embed!("status")),
    ("stepper", embed!("stepper")),
    ("switch", embed!("switch")),
    ("table", embed!("table")),
    ("tabs", embed!("tabs")),
    ("textarea", embed!("textarea")),
    ("theme_toggle", embed!("theme_toggle")),
    ("toaster", embed!("toaster")),
    ("toggle_group", embed!("toggle_group")),
    ("tooltip", embed!("tooltip")),
];
